# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabs.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.Pregunta1 = QtWidgets.QWidget()
        self.Pregunta1.setObjectName("Pregunta1")
        self.comboBox_Ori = QtWidgets.QComboBox(self.Pregunta1)
        self.comboBox_Ori.setGeometry(QtCore.QRect(240, 120, 181, 21))
        self.comboBox_Ori.setObjectName("comboBox_Ori")
        self.comboBox_Ocu = QtWidgets.QComboBox(self.Pregunta1)
        self.comboBox_Ocu.setGeometry(QtCore.QRect(10, 120, 201, 21))
        self.comboBox_Ocu.setObjectName("comboBox_Ocu")
        self.comboBox_Med = QtWidgets.QComboBox(self.Pregunta1)
        self.comboBox_Med.setGeometry(QtCore.QRect(440, 120, 171, 21))
        self.comboBox_Med.setObjectName("comboBox_Med")
        self.label_Pregunta = QtWidgets.QLabel(self.Pregunta1)
        self.label_Pregunta.setGeometry(QtCore.QRect(50, 30, 701, 31))
        self.label_Pregunta.setObjectName("label_Pregunta")
        self.label_7 = QtWidgets.QLabel(self.Pregunta1)
        self.label_7.setGeometry(QtCore.QRect(0, 270, 711, 41))
        self.label_7.setObjectName("label_7")
        self.CancelOK_tab1 = QtWidgets.QDialogButtonBox(self.Pregunta1)
        self.CancelOK_tab1.setGeometry(QtCore.QRect(290, 430, 166, 25))
        self.CancelOK_tab1.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.CancelOK_tab1.setObjectName("CancelOK_tab1")
        self.label_8 = QtWidgets.QLabel(self.Pregunta1)
        self.label_8.setGeometry(QtCore.QRect(0, 310, 711, 41))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.Pregunta1)
        self.label_9.setGeometry(QtCore.QRect(0, 350, 711, 41))
        self.label_9.setObjectName("label_9")
        self.label_1 = QtWidgets.QLabel(self.Pregunta1)
        self.label_1.setGeometry(QtCore.QRect(10, 70, 81, 41))
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.Pregunta1)
        self.label_2.setGeometry(QtCore.QRect(240, 70, 81, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Pregunta1)
        self.label_3.setGeometry(QtCore.QRect(440, 70, 81, 41))
        self.label_3.setObjectName("label_3")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.Pregunta1)
        self.lineEdit_1.setGeometry(QtCore.QRect(330, 210, 101, 25))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.label_archivo = QtWidgets.QLabel(self.Pregunta1)
        self.label_archivo.setGeometry(QtCore.QRect(210, 210, 121, 17))
        self.label_archivo.setObjectName("label_archivo")
        self.tabWidget.addTab(self.Pregunta1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_Pregunta_2 = QtWidgets.QLabel(self.tab_2)
        self.label_Pregunta_2.setGeometry(QtCore.QRect(150, 30, 701, 31))
        self.label_Pregunta_2.setObjectName("label_Pregunta_2")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(60, 100, 81, 41))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(490, 100, 81, 41))
        self.label_14.setObjectName("label_14")
        self.lineEdit_Arch2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_Arch2.setGeometry(QtCore.QRect(340, 330, 101, 25))
        self.lineEdit_Arch2.setObjectName("lineEdit_Arch2")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(290, 100, 81, 41))
        self.label_15.setObjectName("label_15")
        self.comboBox_Ori_3 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_Ori_3.setGeometry(QtCore.QRect(290, 150, 181, 21))
        self.comboBox_Ori_3.setObjectName("comboBox_Ori_3")
        self.comboBox_Ocu_3 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_Ocu_3.setGeometry(QtCore.QRect(60, 150, 201, 21))
        self.comboBox_Ocu_3.setObjectName("comboBox_Ocu_3")
        self.comboBox_Med_3 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_Med_3.setGeometry(QtCore.QRect(490, 150, 171, 21))
        self.comboBox_Med_3.setObjectName("comboBox_Med_3")
        self.comboBox_Nivel = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_Nivel.setGeometry(QtCore.QRect(130, 230, 86, 25))
        self.comboBox_Nivel.setObjectName("comboBox_Nivel")
        self.comboBox_Nivel.addItem("")
        self.comboBox_Nivel.addItem("")
        self.comboBox_Nivel.addItem("")
        self.comboBox_Nivel.addItem("")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(450, 230, 51, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_Lim1 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_Lim1.setGeometry(QtCore.QRect(270, 230, 51, 25))
        self.lineEdit_Lim1.setObjectName("lineEdit_Lim1")
        self.lineEdit_Lim2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_Lim2.setGeometry(QtCore.QRect(450, 230, 51, 25))
        self.lineEdit_Lim2.setObjectName("lineEdit_Lim2")
        self.label_archivo_4 = QtWidgets.QLabel(self.tab_2)
        self.label_archivo_4.setGeometry(QtCore.QRect(10, 230, 121, 16))
        self.label_archivo_4.setObjectName("label_archivo_4")
        self.label_archivo_5 = QtWidgets.QLabel(self.tab_2)
        self.label_archivo_5.setGeometry(QtCore.QRect(270, 260, 61, 16))
        self.label_archivo_5.setObjectName("label_archivo_5")
        self.label_archivo_6 = QtWidgets.QLabel(self.tab_2)
        self.label_archivo_6.setGeometry(QtCore.QRect(450, 260, 61, 16))
        self.label_archivo_6.setObjectName("label_archivo_6")
        self.label_archivo_7 = QtWidgets.QLabel(self.tab_2)
        self.label_archivo_7.setGeometry(QtCore.QRect(210, 330, 121, 17))
        self.label_archivo_7.setObjectName("label_archivo_7")
        self.label_Pregunta_5 = QtWidgets.QLabel(self.tab_2)
        self.label_Pregunta_5.setGeometry(QtCore.QRect(0, 380, 731, 31))
        self.label_Pregunta_5.setObjectName("label_Pregunta_5")
        self.label_Pregunta_6 = QtWidgets.QLabel(self.tab_2)
        self.label_Pregunta_6.setGeometry(QtCore.QRect(0, 400, 731, 31))
        self.label_Pregunta_6.setObjectName("label_Pregunta_6")
        self.label_Pregunta_7 = QtWidgets.QLabel(self.tab_2)
        self.label_Pregunta_7.setGeometry(QtCore.QRect(0, 420, 731, 31))
        self.label_Pregunta_7.setObjectName("label_Pregunta_7")
        self.CancelOK_tab2 = QtWidgets.QDialogButtonBox(self.tab_2)
        self.CancelOK_tab2.setGeometry(QtCore.QRect(270, 470, 166, 25))
        self.CancelOK_tab2.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.CancelOK_tab2.setObjectName("CancelOK_tab2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_Pregunta_3 = QtWidgets.QLabel(self.tab_3)
        self.label_Pregunta_3.setGeometry(QtCore.QRect(70, 40, 701, 31))
        self.label_Pregunta_3.setObjectName("label_Pregunta_3")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(70, 100, 81, 41))
        self.label_16.setObjectName("label_16")
        self.comboBox_Sala_1 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_Sala_1.setGeometry(QtCore.QRect(70, 150, 201, 21))
        self.comboBox_Sala_1.setObjectName("comboBox_Sala_1")
        self.comboBox_Sala_1.addItem("")
        self.comboBox_Sala_1.addItem("")
        self.comboBox_Sala_1.addItem("")
        self.comboBox_Sala_1.addItem("")
        self.comboBox_Sala_1.addItem("")
        self.comboBox_Sala_1.addItem("")
        self.comboBox_Sala_1.addItem("")
        self.comboBox_Ori_4 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_Ori_4.setGeometry(QtCore.QRect(360, 150, 201, 21))
        self.comboBox_Ori_4.setObjectName("comboBox_Ori_4")
        self.comboBox_Ori_4.addItem("")
        self.comboBox_Ori_4.addItem("")
        self.comboBox_Ori_4.addItem("")
        self.comboBox_Ori_4.addItem("")
        self.comboBox_Ori_4.addItem("")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(360, 100, 81, 41))
        self.label_17.setObjectName("label_17")
        self.CancelOK_tab3_1 = QtWidgets.QDialogButtonBox(self.tab_3)
        self.CancelOK_tab3_1.setGeometry(QtCore.QRect(280, 380, 166, 25))
        self.CancelOK_tab3_1.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.CancelOK_tab3_1.setObjectName("CancelOK_tab3_1")
        self.label_archivo_8 = QtWidgets.QLabel(self.tab_3)
        self.label_archivo_8.setGeometry(QtCore.QRect(190, 320, 121, 17))
        self.label_archivo_8.setObjectName("label_archivo_8")
        self.lineEdit_Arch2_2 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_Arch2_2.setGeometry(QtCore.QRect(320, 320, 101, 25))
        self.lineEdit_Arch2_2.setObjectName("lineEdit_Arch2_2")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.comboBox = QtWidgets.QComboBox(self.tab_4)
        self.comboBox.setGeometry(QtCore.QRect(20, 110, 201, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_2.setGeometry(QtCore.QRect(250, 110, 181, 21))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(20, 190, 91, 17))
        self.label_4.setObjectName("label_4")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.tab_4)
        self.dateTimeEdit.setGeometry(QtCore.QRect(110, 190, 194, 26))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(20, 240, 81, 17))
        self.label_5.setObjectName("label_5")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.tab_4)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(110, 240, 194, 26))
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.CancelOK_tab4 = QtWidgets.QDialogButtonBox(self.tab_4)
        self.CancelOK_tab4.setGeometry(QtCore.QRect(330, 470, 166, 25))
        self.CancelOK_tab4.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.CancelOK_tab4.setObjectName("CancelOK_tab4")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_3.setGeometry(QtCore.QRect(470, 110, 171, 21))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(660, 180, 101, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(530, 180, 121, 17))
        self.label_6.setObjectName("label_6")
        self.label_Pregunta_4 = QtWidgets.QLabel(self.tab_4)
        self.label_Pregunta_4.setGeometry(QtCore.QRect(10, 20, 761, 31))
        self.label_Pregunta_4.setObjectName("label_Pregunta_4")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(20, 60, 81, 41))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(250, 60, 81, 41))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(470, 60, 81, 41))
        self.label_12.setObjectName("label_12")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_5.setGeometry(QtCore.QRect(360, 190, 101, 25))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_6.setGeometry(QtCore.QRect(360, 240, 101, 25))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(20, 320, 511, 17))
        self.label.setObjectName("label")
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(20, 350, 651, 17))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(20, 380, 651, 17))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setGeometry(QtCore.QRect(10, 430, 791, 17))
        self.label_20.setObjectName("label_20")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(500, 80, 81, 41))
        self.label_21.setObjectName("label_21")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab)
        self.comboBox_4.setGeometry(QtCore.QRect(500, 130, 171, 21))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_44 = QtWidgets.QLabel(self.tab)
        self.label_44.setGeometry(QtCore.QRect(270, 80, 81, 41))
        self.label_44.setObjectName("label_44")
        self.comboBox_13 = QtWidgets.QComboBox(self.tab)
        self.comboBox_13.setGeometry(QtCore.QRect(270, 130, 181, 21))
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.label_45 = QtWidgets.QLabel(self.tab)
        self.label_45.setGeometry(QtCore.QRect(30, 80, 81, 41))
        self.label_45.setObjectName("label_45")
        self.comboBox_14 = QtWidgets.QComboBox(self.tab)
        self.comboBox_14.setGeometry(QtCore.QRect(30, 130, 201, 21))
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_15 = QtWidgets.QComboBox(self.tab)
        self.comboBox_15.setGeometry(QtCore.QRect(20, 230, 201, 21))
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.label_46 = QtWidgets.QLabel(self.tab)
        self.label_46.setGeometry(QtCore.QRect(20, 180, 81, 41))
        self.label_46.setObjectName("label_46")
        self.label_archivo_14 = QtWidgets.QLabel(self.tab)
        self.label_archivo_14.setGeometry(QtCore.QRect(470, 330, 61, 16))
        self.label_archivo_14.setObjectName("label_archivo_14")
        self.lineEdit_Lim2_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_Lim2_3.setGeometry(QtCore.QRect(470, 300, 51, 25))
        self.lineEdit_Lim2_3.setObjectName("lineEdit_Lim2_3")
        self.label_archivo_15 = QtWidgets.QLabel(self.tab)
        self.label_archivo_15.setGeometry(QtCore.QRect(30, 300, 121, 16))
        self.label_archivo_15.setObjectName("label_archivo_15")
        self.label_archivo_16 = QtWidgets.QLabel(self.tab)
        self.label_archivo_16.setGeometry(QtCore.QRect(290, 330, 61, 16))
        self.label_archivo_16.setObjectName("label_archivo_16")
        self.comboBox_Nivel_3 = QtWidgets.QComboBox(self.tab)
        self.comboBox_Nivel_3.setGeometry(QtCore.QRect(150, 300, 86, 25))
        self.comboBox_Nivel_3.setObjectName("comboBox_Nivel_3")
        self.comboBox_Nivel_3.addItem("")
        self.comboBox_Nivel_3.addItem("")
        self.comboBox_Nivel_3.addItem("")
        self.comboBox_Nivel_3.addItem("")
        self.lineEdit_Lim1_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_Lim1_3.setGeometry(QtCore.QRect(290, 300, 51, 25))
        self.lineEdit_Lim1_3.setObjectName("lineEdit_Lim1_3")
        self.lineEdit_Arch2_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_Arch2_5.setGeometry(QtCore.QRect(360, 400, 101, 25))
        self.lineEdit_Arch2_5.setObjectName("lineEdit_Arch2_5")
        self.CancelOK_estacion = QtWidgets.QDialogButtonBox(self.tab)
        self.CancelOK_estacion.setGeometry(QtCore.QRect(270, 460, 166, 25))
        self.CancelOK_estacion.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.CancelOK_estacion.setObjectName("CancelOK_estacion")
        self.label_archivo_17 = QtWidgets.QLabel(self.tab)
        self.label_archivo_17.setGeometry(QtCore.QRect(230, 400, 121, 17))
        self.label_archivo_17.setObjectName("label_archivo_17")
        self.comboBox_16 = QtWidgets.QComboBox(self.tab)
        self.comboBox_16.setGeometry(QtCore.QRect(280, 230, 201, 21))
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.label_47 = QtWidgets.QLabel(self.tab)
        self.label_47.setGeometry(QtCore.QRect(280, 180, 81, 41))
        self.label_47.setObjectName("label_47")
        self.label_Pregunta_15 = QtWidgets.QLabel(self.tab)
        self.label_Pregunta_15.setGeometry(QtCore.QRect(20, 30, 761, 31))
        self.label_Pregunta_15.setObjectName("label_Pregunta_15")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Pregunta.setText(_translate("MainWindow", "Tipo de pregunta: ¿Cual es la temperatura actual de cada Sala? "))
        self.label_7.setText(_translate("MainWindow", "-Puedes preguntar por temperatura, consumo de agua, nivel de humedad, nivel de batería..."))
        self.label_8.setText(_translate("MainWindow", "-Puedes seleccionar la orientación de las salas, así como si están ocupadas o no"))
        self.label_9.setText(_translate("MainWindow", "-Es necesario introducir el nombre del archivo, que se guardará en formato .csv"))
        self.label_1.setText(_translate("MainWindow", "Ocupación:"))
        self.label_2.setText(_translate("MainWindow", "Orientación:"))
        self.label_3.setText(_translate("MainWindow", "Medición:"))
        self.label_archivo.setText(_translate("MainWindow", "Nombre Archivo:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Pregunta1), _translate("MainWindow", "Tab 1"))
        self.label_Pregunta_2.setText(_translate("MainWindow", "Tipo de pregunta: ¿Que salas tiene una temperatura superior a 10 grados? "))
        self.label_13.setText(_translate("MainWindow", "Ocupación:"))
        self.label_14.setText(_translate("MainWindow", "Medición:"))
        self.label_15.setText(_translate("MainWindow", "Orientación:"))
        self.comboBox_Nivel.setItemText(0, _translate("MainWindow", "Nivel"))
        self.comboBox_Nivel.setItemText(1, _translate("MainWindow", "Mayor"))
        self.comboBox_Nivel.setItemText(2, _translate("MainWindow", "Menor"))
        self.comboBox_Nivel.setItemText(3, _translate("MainWindow", "Entre"))
        self.label_archivo_4.setText(_translate("MainWindow", "Comparación:"))
        self.label_archivo_5.setText(_translate("MainWindow", "Límite 1"))
        self.label_archivo_6.setText(_translate("MainWindow", "Límite 2"))
        self.label_archivo_7.setText(_translate("MainWindow", "Nombre Archivo:"))
        self.label_Pregunta_5.setText(_translate("MainWindow", "-Puedes elegir entre mayor o menor para un determinado límite de medida, introduciendo valor en Límite 1"))
        self.label_Pregunta_6.setText(_translate("MainWindow", "-Puedes elegir obtener las salas con una medida entre dos valores introduciendo valor en Límite 1 y Límite 2"))
        self.label_Pregunta_7.setText(_translate("MainWindow", "-Introduce el nombre del archivo que se guardará en formato csv"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.label_Pregunta_3.setText(_translate("MainWindow", "Tipo de pregunta: ¿Que salas tienen una orientación al oeste? "))
        self.label_16.setText(_translate("MainWindow", "Tipo de Sala:"))
        self.comboBox_Sala_1.setItemText(0, _translate("MainWindow", "Sala"))
        self.comboBox_Sala_1.setItemText(1, _translate("MainWindow", "Comun"))
        self.comboBox_Sala_1.setItemText(2, _translate("MainWindow", "Aula"))
        self.comboBox_Sala_1.setItemText(3, _translate("MainWindow", "Despacho"))
        self.comboBox_Sala_1.setItemText(4, _translate("MainWindow", "Aseo"))
        self.comboBox_Sala_1.setItemText(5, _translate("MainWindow", "Laboratorio"))
        self.comboBox_Sala_1.setItemText(6, _translate("MainWindow", "Cuarto"))
        self.comboBox_Ori_4.setItemText(0, _translate("MainWindow", "Orientacion"))
        self.comboBox_Ori_4.setItemText(1, _translate("MainWindow", "Norte"))
        self.comboBox_Ori_4.setItemText(2, _translate("MainWindow", "Sur"))
        self.comboBox_Ori_4.setItemText(3, _translate("MainWindow", "Este"))
        self.comboBox_Ori_4.setItemText(4, _translate("MainWindow", "Oeste"))
        self.label_17.setText(_translate("MainWindow", "Orientacion:"))
        self.label_archivo_8.setText(_translate("MainWindow", "Nombre Archivo:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Salas ocupadas"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Salas no ocupadas"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Orientación"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Norte"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Sur"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Este"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Oeste"))
        self.label_4.setText(_translate("MainWindow", "Fecha Inicio:"))
        self.label_5.setText(_translate("MainWindow", "Fecha Final:"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Medida"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Temperatura"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Consumo Agua"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Nivel Humedad"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "Nivel Batería"))
        self.label_6.setText(_translate("MainWindow", "Nombre Archivo:"))
        self.label_Pregunta_4.setText(_translate("MainWindow", "Tipo de pregunta: ¿Cual es la media de temperatura entre el 14/03/2019 y el 15/04/2019 entre las 10:30 y 12:30? "))
        self.label_10.setText(_translate("MainWindow", "Ocupación:"))
        self.label_11.setText(_translate("MainWindow", "Orientación:"))
        self.label_12.setText(_translate("MainWindow", "Medición:"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Hora Inicio"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "00"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "01"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "02"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "03"))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "04"))
        self.comboBox_5.setItemText(6, _translate("MainWindow", "05"))
        self.comboBox_5.setItemText(7, _translate("MainWindow", "06"))
        self.comboBox_5.setItemText(8, _translate("MainWindow", "07"))
        self.comboBox_5.setItemText(9, _translate("MainWindow", "08"))
        self.comboBox_5.setItemText(10, _translate("MainWindow", "09"))
        self.comboBox_5.setItemText(11, _translate("MainWindow", "10"))
        self.comboBox_5.setItemText(12, _translate("MainWindow", "11"))
        self.comboBox_5.setItemText(13, _translate("MainWindow", "12"))
        self.comboBox_5.setItemText(14, _translate("MainWindow", "13"))
        self.comboBox_5.setItemText(15, _translate("MainWindow", "14"))
        self.comboBox_5.setItemText(16, _translate("MainWindow", "15"))
        self.comboBox_5.setItemText(17, _translate("MainWindow", "16"))
        self.comboBox_5.setItemText(18, _translate("MainWindow", "17"))
        self.comboBox_5.setItemText(19, _translate("MainWindow", "18"))
        self.comboBox_5.setItemText(20, _translate("MainWindow", "19"))
        self.comboBox_5.setItemText(21, _translate("MainWindow", "20"))
        self.comboBox_5.setItemText(22, _translate("MainWindow", "21"))
        self.comboBox_5.setItemText(23, _translate("MainWindow", "22"))
        self.comboBox_5.setItemText(24, _translate("MainWindow", "23"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Hora Final"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "00"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "01"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "02"))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "03"))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "04"))
        self.comboBox_6.setItemText(6, _translate("MainWindow", "05"))
        self.comboBox_6.setItemText(7, _translate("MainWindow", "06"))
        self.comboBox_6.setItemText(8, _translate("MainWindow", "07"))
        self.comboBox_6.setItemText(9, _translate("MainWindow", "08"))
        self.comboBox_6.setItemText(10, _translate("MainWindow", "09"))
        self.comboBox_6.setItemText(11, _translate("MainWindow", "10"))
        self.comboBox_6.setItemText(12, _translate("MainWindow", "11"))
        self.comboBox_6.setItemText(13, _translate("MainWindow", "12"))
        self.comboBox_6.setItemText(14, _translate("MainWindow", "13"))
        self.comboBox_6.setItemText(15, _translate("MainWindow", "14"))
        self.comboBox_6.setItemText(16, _translate("MainWindow", "15"))
        self.comboBox_6.setItemText(17, _translate("MainWindow", "16"))
        self.comboBox_6.setItemText(18, _translate("MainWindow", "17"))
        self.comboBox_6.setItemText(19, _translate("MainWindow", "18"))
        self.comboBox_6.setItemText(20, _translate("MainWindow", "19"))
        self.comboBox_6.setItemText(21, _translate("MainWindow", "20"))
        self.comboBox_6.setItemText(22, _translate("MainWindow", "21"))
        self.comboBox_6.setItemText(23, _translate("MainWindow", "22"))
        self.comboBox_6.setItemText(24, _translate("MainWindow", "23"))
        self.label.setText(_translate("MainWindow", "-Para obtener la media de los últimos 365 días no modificar fechas ni hora"))
        self.label_18.setText(_translate("MainWindow", "-Para obtener la media entre dos días sin tener en cuenta horas, no modificar los campos Hora"))
        self.label_19.setText(_translate("MainWindow", "-Para obtener la media entre dos días teniendo en cuenta horas, seleccionar las horas deseadas"))
        self.label_20.setText(_translate("MainWindow", "El campo de ocupación se incluye por si en el futuro se pudiese hacer este tipo de consultas teniendo en cuenta ese campo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Page"))
        self.label_21.setText(_translate("MainWindow", "Medición:"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Medida"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Temperatura"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Consumo Agua"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Nivel Humedad"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "Nivel Batería"))
        self.label_44.setText(_translate("MainWindow", "Orientación:"))
        self.comboBox_13.setItemText(0, _translate("MainWindow", "Orientación"))
        self.comboBox_13.setItemText(1, _translate("MainWindow", "Norte"))
        self.comboBox_13.setItemText(2, _translate("MainWindow", "Sur"))
        self.comboBox_13.setItemText(3, _translate("MainWindow", "Este"))
        self.comboBox_13.setItemText(4, _translate("MainWindow", "Oeste"))
        self.label_45.setText(_translate("MainWindow", "Ocupación:"))
        self.comboBox_14.setItemText(0, _translate("MainWindow", "Salas ocupadas"))
        self.comboBox_14.setItemText(1, _translate("MainWindow", "Salas no ocupadas"))
        self.comboBox_15.setItemText(0, _translate("MainWindow", "Estación"))
        self.comboBox_15.setItemText(1, _translate("MainWindow", "Verano"))
        self.comboBox_15.setItemText(2, _translate("MainWindow", "Primavera"))
        self.comboBox_15.setItemText(3, _translate("MainWindow", "Otoño"))
        self.comboBox_15.setItemText(4, _translate("MainWindow", "Invierno"))
        self.label_46.setText(_translate("MainWindow", "Estación:"))
        self.label_archivo_14.setText(_translate("MainWindow", "Límite 2"))
        self.label_archivo_15.setText(_translate("MainWindow", "Comparación:"))
        self.label_archivo_16.setText(_translate("MainWindow", "Límite 1"))
        self.comboBox_Nivel_3.setItemText(0, _translate("MainWindow", "Nivel"))
        self.comboBox_Nivel_3.setItemText(1, _translate("MainWindow", "Mayor"))
        self.comboBox_Nivel_3.setItemText(2, _translate("MainWindow", "Menor"))
        self.comboBox_Nivel_3.setItemText(3, _translate("MainWindow", "Entre"))
        self.label_archivo_17.setText(_translate("MainWindow", "Nombre Archivo:"))
        self.comboBox_16.setItemText(0, _translate("MainWindow", "Año"))
        self.comboBox_16.setItemText(1, _translate("MainWindow", "2016"))
        self.comboBox_16.setItemText(2, _translate("MainWindow", "2017"))
        self.comboBox_16.setItemText(3, _translate("MainWindow", "2018"))
        self.comboBox_16.setItemText(4, _translate("MainWindow", "2019"))
        self.comboBox_16.setItemText(5, _translate("MainWindow", "2020"))
        self.label_47.setText(_translate("MainWindow", "Año"))
        self.label_Pregunta_15.setText(_translate("MainWindow", "Tipo de pregunta: ¿Qué salas tienen una temperatura media superior a 15 grados en verano?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Page"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
